distributable:
  url: https://github.com/surrealdb/surrealdb/archive/refs/tags/v1.0.0-beta.8.tar.gz
  strip-components: 1

provides:
  - bin/surreal

versions:
  - 0.0.0
  # github: surrealdb/surrealdb # FIXME once there has been an official release
  # strip: /v/

build:
  dependencies:
    rust-lang.org: '>=1.60'
    rust-lang.org/cargo: '*'
  script:
    cargo install --locked --path . --root {{prefix}}

test:
  script: |
    surreal version

